version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data